using System;
using System.Collections.Generic;

namespace Models
{
    /// <summary>
    /// Post file type.
    /// </summary>
    public class PostFileType
    {
        public const string Cover = "Cover";
        public const string CroppedCover = "Cropped";
        public const string Photo = "Photo";
        public const string Audio = "Audio";
        public const string Video = "Video";
        public const string File = "File";

        public readonly static Dictionary<string, string[]> Map = new Dictionary<string, string[]>() {

            #region Big freaking list of mime types
            
            //{".3g2", new string[] { Video, "video/3gpp2" } },
            //{".3gp", new string[] { Video, "video/3gpp" } },
            //{".3gp2", new string[] { Video, "video/3gpp2" } },
            //{".3gpp", new string[] { Video, "video/3gpp" } },
            //{".aa", new string[] { Audio, "audio/audible"} },
            //{".AAC", new string[] { Audio, "audio/aac"} },
            //{".aax", new string[] { Audio, "audio/vnd.audible.aax"} },
            //{".ac3", new string[] { Audio, "audio/ac3"} },
            //{".ADT", new string[] { Audio, "audio/vnd.dlna.adts"} },
            //{".ADTS", new string[] { Audio, "audio/aac"} },
            //{".aif", new string[] { Audio, "audio/aiff"} },
            //{".aifc", new string[] { Audio, "audio/aiff"} },
            //{".aiff", new string[] { Audio, "audio/aiff"} },
            //{".amc", new string[] { Video, "application/mpeg" } },
            {".art", new string[] { Photo, "image/x-jg"} },
            //{".asf", new string[] { Video, "video/x-ms-asf"} },
            //{".asr", new string[] { Video, "video/x-ms-asf"} },
            //{".asx", new string[] { Video, "video/x-ms-asf"} },
            //{".au", new string[] { Audio, "audio/basic"} },
            //{".avi", new string[] { Video, "video/x-msvideo"} },
            //{".axa", new string[] { Audio, "audio/annodex"} },
            //{".axv", new string[] { Video, "video/annodex"} },
            {".bmp", new string[] { Photo, "image/bmp"} },
            //{".cdda", new string[] { Audio, "audio/aiff"} },
            {".cmx", new string[] { Photo, "image/x-cmx"} },
            {".cod", new string[] { Photo, "image/cis-cod"} },
            {".dib", new string[] { Photo, "image/bmp"} },
            //{".dif", new string[] { Video, "video/x-dv"} },
            //{".divx", new string[] { Video, "video/divx"} },
            //{".dv", new string[] { Video, "video/x-dv"} },
            //{".dvi", new string[] { Video, "application/x-dvi" } },
            //{".flac", new string[] { Audio, "audio/flac"} },
            //{".flv", new string[] { Video, "video/x-flv"} },
            {".gif", new string[] { Photo, "image/gif"} },
            //{".gsm", new string[] { Audio, "audio/x-gsm"} },
            {".ico", new string[] { Photo, "image/x-icon"} },
            {".ief", new string[] { Photo, "image/ief"} },
            //{".IVF", new string[] { Video, "video/x-ivf"} },
            {".jfif", new string[] { Photo, "image/pjpeg"} },
            {".jpe", new string[] { Photo, "image/jpeg"} },
            {".jpeg", new string[] { Photo, "image/jpeg"} },
            {".jpg", new string[] { Photo, "image/jpeg"} },
            //{".lsf", new string[] { Video, "video/x-la-asf"} },
            //{".lsx", new string[] { Video, "video/x-la-asf"} },
            //{".m1v", new string[] { Video, "video/mpeg"} },
            //{".m2t", new string[] { Video, "video/vnd.dlna.mpeg-tts"} },
            //{".m2ts", new string[] { Video, "video/vnd.dlna.mpeg-tts"} },
            //{".m2v", new string[] { Video, "video/mpeg"} },
            //{".m3u", new string[] { Audio, "audio/x-mpegurl"} },
            //{".m3u8", new string[] { Audio, "audio/x-mpegurl"} },
            //{".m4a", new string[] { Audio, "audio/m4a"} },
            //{".m4b", new string[] { Audio, "audio/m4b"} },
            //{".m4p", new string[] { Audio, "audio/m4p"} },
            //{".m4r", new string[] { Audio, "audio/x-m4r"} },
            //{".m4v", new string[] { Video, "video/x-m4v"} },
            {".mac", new string[] { Photo, "image/x-macpaint"} },
            //{".mid", new string[] { Audio, "audio/mid"} },
            //{".midi", new string[] { Audio, "audio/mid"} },
            //{".mod", new string[] { Video, "video/mpeg"} },
            //{".mov", new string[] { Video, "video/quicktime"} },
            //{".movie", new string[] { Video, "video/x-sgi-movie"} },
            //{".mp2", new string[] { Video, "video/mpeg"} },
            //{".mp2v", new string[] { Video, "video/mpeg"} },
            {".mp3", new string[] { Audio, "audio/mpeg"} },
            {".mp4", new string[] { Video, "video/mp4"} },
            //{".mp4v", new string[] { Video, "video/mp4"} },
            //{".mpa", new string[] { Video, "video/mpeg"} },
            //{".mpe", new string[] { Video, "video/mpeg"} },
            //{".mpeg", new string[] { Video, "video/mpeg"} },
            //{".mpg", new string[] { Video, "video/mpeg"} },
            //{".mpv2", new string[] { Video, "video/mpeg"} },
            //{".mqv", new string[] { Video, "video/quicktime"} },
            //{".mts", new string[] { Video, "video/vnd.dlna.mpeg-tts"} },
            //{".nsc", new string[] { Video, "video/x-ms-asf"} },
            {".oga", new string[] { Audio, "audio/ogg"} },
            {".ogg", new string[] { Audio, "audio/ogg"} },
            {".ogv", new string[] { Video, "video/ogg"} },
            //{".opus", new string[] { Audio, "audio/ogg"} },
            {".pct", new string[] { Photo, "image/pict"} },
            {".pgm", new string[] { Photo, "image/x-portable-graymap"} },
            {".pic", new string[] { Photo, "image/pict"} },
            {".pict", new string[] { Photo, "image/pict"} },
            //{".pls", new string[] { Audio, "audio/scpls"} },
            {".png", new string[] { Photo, "image/png"} },
            {".pnm", new string[] { Photo, "image/x-portable-anymap"} },
            {".pnt", new string[] { Photo, "image/x-macpaint"} },
            {".pntg", new string[] { Photo, "image/x-macpaint"} },
            {".pnz", new string[] { Photo, "image/png"} },
            {".ppm", new string[] { Photo, "image/x-portable-pixmap"} },
            //{".qt", new string[] { Video, "video/quicktime"} },
            {".qti", new string[] { Photo, "image/x-quicktime"} },
            {".qtif", new string[] { Photo, "image/x-quicktime"} },
            //{".ra", new string[] { Audio, "audio/x-pn-realaudio"} },
            //{".ram", new string[] { Audio, "audio/x-pn-realaudio"} },
            {".ras", new string[] { Photo, "image/x-cmu-raster"} },
            {".rf", new string[] { Photo, "image/vnd.rn-realflash"} },
            {".rgb", new string[] { Photo, "image/x-rgb"} },
            //{".rmi", new string[] { Audio, "audio/mid"} },
            //{".rpm", new string[] { Audio, "audio/x-pn-realaudio-plugin"} },
            //{".sd2", new string[] { Audio, "audio/x-sd2"} },
            //{".smd", new string[] { Audio, "audio/x-smd"} },
            //{".smx", new string[] { Audio, "audio/x-smd"} },
            //{".smz", new string[] { Audio, "audio/x-smd"} },
            //{".snd", new string[] { Audio, "audio/basic"} },
            //{".spx", new string[] { Audio, "audio/ogg"} },
            {".svg", new string[] { Photo, "image/svg+xml"} },
            {".tif", new string[] { Photo, "image/tiff"} },
            {".tiff", new string[] { Photo, "image/tiff"} },
            //{".ts", new string[] { Video, "video/vnd.dlna.mpeg-tts"} },
            //{".tts", new string[] { Video, "video/vnd.dlna.mpeg-tts"} },
            //{".vbk", new string[] { Video, "video/mpeg"} },
            {".wav", new string[] { Audio, "audio/wav"} },
            //{".wave", new string[] { Audio, "audio/wav"} },
            //{".wax", new string[] { Audio, "audio/x-ms-wax"} },
            {".wbmp", new string[] { Photo, "image/vnd.wap.wbmp"} },
            {".wdp", new string[] { Photo, "image/vnd.ms-photo"} },
            {".webm", new string[] { Video, "video/webm"} },
            {".webp", new string[] { Photo, "image/webp"} },
            //{".wm", new string[] { Video, "video/x-ms-wm"} },
            //{".wma", new string[] { Audio, "audio/x-ms-wma"} },
            //{".wmp", new string[] { Video, "video/x-ms-wmp"} },
            //{".wmv", new string[] { Video, "video/x-ms-wmv"} },
            //{".wmx", new string[] { Video, "video/x-ms-wmx"} },
            //{".wvx", new string[] { Video, "video/x-ms-wvx"} },
            {".xbm", new string[] { Photo, "image/x-xbitmap"} },
            {".xpm", new string[] { Photo, "image/x-xpixmap"} },

            #endregion

        };
    }
}